name: apivideo_live_stream_platform_interface
description: A common platform interface for the api.video live stream plugin.
repository: https://github.com/apivideo/api.video-flutter-live-stream/packages/live_stream_platform_interface
issue_tracker: https://github.com/apivideo/api.video-flutter-live-stream/issues
homepage: https://api.video
version: 1.3.0

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.7
  json_annotation: ^4.9.0
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.8.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
